# Generated by Django 3.2.18 on 2023-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230326_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Blekinge län', 'Blekinge län'), ('Dalarnas län', 'Dalarnas län'), ('Gotlands län', 'Gotlands län'), ('Gävleborgs län', 'Gävleborgs län'), ('Hallands län', 'Hallands län'), ('Jämtlands län', 'Jämtlands län'), ('Jönköpings län', 'Jönköpings län'), ('Kalmar län', 'Kalmar län'), ('Kronobergs län', 'Kronobergs län'), ('Norrbottens län', 'Norrbottens län'), ('Skåne län', 'Skåne län'), ('Stockholms län', 'Stockholms län'), ('Södermanlands län', 'Södermanlands län'), ('Uppsala län', 'Uppsala län'), ('Värmlands län', 'Värmlands län'), ('Västerbottens län', 'Västerbottens län'), ('Västernorrlands län', 'Västernorrlands län'), ('Västmanlands län', 'Västmanlands län'), ('Västra Götalands län', 'Västra Götalands län'), ('Örebro län', 'Örebro län'), ('Östergötlands län', 'Östergötlands län')], default='Jönköpings län', max_length=100),
        ),
    ]
